name: pomodoro_timer
description: Aplicativo Flutter de Timer Pomodoro.
version: 0.2.0+2
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.2.3
  wakelock_plus: ^1.4.0
  flutter_local_notifications: ^17.2.1
  flutter_native_splash: ^2.4.6
  change_app_package_name: ^1.5.0

dev_dependencies:
    flutter_lints: ^3.0.2

flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: "#29cbcb"
  adaptive_icon_foreground: assets/icon/icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
  image_path_android: assets/icon/AppIcons/android/mipmap-xxxhdpi/ic_launcher.png
  image_path_ios: assets/icon/AppIcons/Assets.xcassets/AppIcon.appiconset/1024.png
